name: API Tests
on:
  push:
    branches:
      - main
      - feat-github_action_CI

  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Karate tag to run'
        required: false
        default: '@smoke'
        type: choice
        options:
          - '@happy-path'
          - '@negative'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven tests
        env:
          DEMO_USERNAME: ${{ secrets.DEMO_USERNAME }}
          DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}
          DEMO_EMAIL: ${{ secrets.DEMO_EMAIL }}
          NEW_USER_PASSWORD: ${{ secrets.NEW_USER_PASSWORD }}
          EXISTING_USERNAME: ${{ secrets.EXISTING_USERNAME }}
          EXISTING_PASSWORD: ${{ secrets.EXISTING_PASSWORD }}
          EXISTING_EMAIL: ${{ secrets.EXISTING_EMAIL }}
        run: mvn clean test -D"karate.options=--tags ${{ inputs.test_tag }}"

      - name: Upload Karate Reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: karate-reports
          path: target/karate-reports/
          overwrite: true

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: cucumber-reports
          path: target/cucumber-html-reports/
          overwrite: true

      - run: echo "The report is generated successfully!"
      - run: echo "🍏 This job's status is ${{ job.status }}."
